# -*- coding: utf-8 -*-
"""
Stage 02 - EXPORTATION - Fields extraction (rule-based: regex + heuristics)

Input : folder with *_extracted.json generated by Stage 01 (exportation)
Output: folder with *_fields.json + _stage02_summary.json

No external deps required (only stdlib).

How it works:
- Joins all pages into a single searchable text with [PAGE N] markers
- Infers doc kind (commercial_invoice, packing_list, draft_bl, certificate_of_origin, container_data)
- Extracts required fields per doc kind
- Outputs JSON with: present/required/value/evidence/method
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------
# Basics
# ---------------------------

def now_iso() -> str:
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S")


def read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_json(path: Path, obj: dict) -> None:
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def squish(s: str) -> str:
    s = (s or "").replace("\r", "\n")
    s = re.sub(r"[ \t]+", " ", s)
    s = re.sub(r"\n{3,}", "\n\n", s)
    return s.strip()


def normalize_for_search(s: str) -> str:
    return squish(s).lower()


def snippet_around(text: str, start: int, end: int, pad: int = 90) -> str:
    a = max(0, start - pad)
    b = min(len(text), end + pad)
    sn = text[a:b].replace("\n", " ")
    sn = re.sub(r"\s{2,}", " ", sn).strip()
    return sn


def parse_number_mixed(raw: str) -> Optional[float]:
    """
    Parse formats:
      - 133.780,00  -> 133780.00
      - 7,980.00    -> 7980.00
      - 29,922,400.- -> 29922400
      - 2100,000    -> 2100.0
    """
    if raw is None:
        return None
    s = str(raw).strip()
    if not s:
        return None

    s = s.replace("KGS", "").replace("KG", "").replace("US$", "").replace("$", "")
    s = s.replace(".-", "").replace(",-", "").replace("–", "-")
    s = re.sub(r"[^\d,.\-]", "", s)

    if not s:
        return None

    last_comma = s.rfind(",")
    last_dot = s.rfind(".")

    if last_comma != -1 and last_dot != -1:
        if last_comma > last_dot:
            # comma decimal, dot thousand
            s = s.replace(".", "")
            s = s.replace(",", ".")
        else:
            # dot decimal, comma thousand
            s = s.replace(",", "")
    elif last_comma != -1:
        # only commas -> assume decimal; if multiple commas, previous are thousand
        parts = s.split(",")
        if len(parts) > 2:
            s = "".join(parts[:-1]) + "." + parts[-1]
        else:
            s = s.replace(",", ".")
    elif last_dot != -1 and s.count(".") > 1:
        # many dots -> keep last as decimal
        parts = s.split(".")
        s = "".join(parts[:-1]) + "." + parts[-1]

    try:
        return float(s)
    except ValueError:
        return None


def parse_cnpj(raw: str) -> Optional[str]:
    if not raw:
        return None
    digits = re.sub(r"\D", "", raw)
    return digits if len(digits) == 14 else None


def parse_phone_candidates(text: str) -> List[str]:
    """
    Heuristic phone capture (BR + international)
    """
    phones = set()
    # +55 11 99999-9999, (11) 99999-9999, 11 99999-9999, +1 876-xxx-xxxx etc.
    patterns = [
        r"\+\d{1,3}\s*\(?\d{1,3}\)?\s*\d{3,5}[-\s]?\d{3,5}[-\s]?\d{0,5}",
        r"\(?\d{2,3}\)?\s*\d{4,5}[-\s]?\d{4}",
    ]
    for pat in patterns:
        for m in re.finditer(pat, text):
            ph = re.sub(r"\s{2,}", " ", m.group(0)).strip()
            if len(ph) >= 8:
                phones.add(ph)
    return sorted(phones)


def rx_first(text: str, pattern: str, flags=re.IGNORECASE | re.MULTILINE) -> Tuple[Optional[str], List[str], str]:
    m = re.search(pattern, text, flags)
    if not m:
        return None, [], "regex"
    val = m.group(1).strip() if m.lastindex else m.group(0).strip()
    ev = [snippet_around(text, m.start(), m.end())]
    return val, ev, "regex"


def rx_findall(text: str, pattern: str, flags=re.IGNORECASE | re.MULTILINE, limit_ev: int = 12) -> Tuple[List[str], List[str], str]:
    out = []
    ev = []
    for m in re.finditer(pattern, text, flags):
        val = m.group(1).strip() if m.lastindex else m.group(0).strip()
        out.append(val)
        if len(ev) < limit_ev:
            ev.append(snippet_around(text, m.start(), m.end()))
    return out, ev, "regex_findall"


def line_after_label(text: str, label_pattern: str, max_lookahead: int = 6) -> Tuple[Optional[str], List[str], str]:
    """
    Find a line matching label_pattern and return the next non-empty line.
    """
    lines = [ln.rstrip() for ln in text.splitlines()]
    for i, ln in enumerate(lines):
        if re.search(label_pattern, ln, re.IGNORECASE):
            for j in range(i + 1, min(i + 1 + max_lookahead, len(lines))):
                nxt = lines[j].strip()
                if nxt:
                    return nxt, [f"{ln.strip()} -> {nxt}"], "line_heuristic"
    return None, [], "line_heuristic"


def inline_after_label(text: str, label_pattern: str) -> Tuple[Optional[str], List[str], str]:
    """
    Find a line matching label_pattern and capture text after it on same line.
    """
    lines = [ln.rstrip() for ln in text.splitlines()]
    for ln in lines:
        m = re.search(label_pattern, ln, re.IGNORECASE)
        if m:
            after = ln[m.end():].strip(" :\t-")
            if after:
                return after, [ln.strip()], "inline_heuristic"
    return None, [], "inline_heuristic"


def make_field(required: bool, value: Any, evidence: List[str], method: str) -> Dict[str, Any]:
    present = value is not None and value != "" and value != [] and value is not False
    return {
        "present": bool(present),
        "required": bool(required),
        "value": value if present else None,
        "evidence": evidence if present else [],
        "method": method
    }


def join_pages(stage01: dict) -> str:
    parts: List[str] = []
    for p in stage01.get("pages", []):
        page_no = p.get("page")
        txt = (p.get("text") or "").strip()
        if txt:
            parts.append(f"[PAGE {page_no}] {txt}")
    return squish("\n\n".join(parts))


# ---------------------------
# Doc kind inference (EXPORTATION)
# ---------------------------

def infer_doc_kind(filename: str, full_text: str) -> str:
    fn = (filename or "").lower()
    t = normalize_for_search(full_text)

    if ("certificate of origin" in t) or ("certificado de origem" in t) or ("certificat d'origine" in t):
        return "certificate_of_origin"

    # Draft BL: common anchors in your examples
    if ("bill of lading" in t) or ("bill of landing" in t) or ("b/lnumber" in t) or ("carrier'sreferencenumber" in t) or ("b/l number" in t):
        return "draft_bl"

    if "packing list" in fn or "packing" in fn or ("packing nr" in t) or ("packing list" in t):
        return "packing_list"

    if "commercial invoice" in fn or "invoice" in fn or ("invoice nr" in t) or ("factura comercial" in t) or ("fatura comercial" in t):
        return "commercial_invoice"

    if "dados cntr" in fn or ("booking:" in t and "container" in t and ("lacre" in t or "seal" in t)):
        return "container_data"

    return "unknown"


# ---------------------------
# Field extraction (EXPORTATION)
# ---------------------------

def ex_commercial_invoice(text: str) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    warnings: List[str] = []
    fields: Dict[str, Dict[str, Any]] = {}

    inv_no, ev, m = line_after_label(text, r"^invoice\s*nr\.?$")
    if not inv_no:
        inv_no, ev, m = inline_after_label(text, r"invoice\s*nr\.?")
    fields["invoice_number"] = make_field(True, inv_no, ev, m)

    date, ev, m = rx_first(text, r"\b(\d{2}/\d{2}/\d{4})\b")
    fields["invoice_date"] = make_field(True, date, ev, m)

    country, ev, m = line_after_label(text, r"^pais\s+de\s+origen\b")
    fields["country_of_origin"] = make_field(True, country, ev, m)

    mode, ev, m = line_after_label(text, r"^via\s+de\s+transporte\b")
    fields["transport_mode"] = make_field(True, mode, ev, m)

    # Ports often appear in header line: "Puerto de Embarque Puerto de Destino"
    pol, ev1, m1 = inline_after_label(text, r"puerto\s+de\s+embarque\s+puerto\s+de\s+destino")
    port_loading = None
    port_destination = None
    if pol:
        # try: split last tokens
        tokens = pol.split()
        # Example: "Maritimo SANTOS PORT KINGSTON"
        # choose last 3/2 tokens as best-effort
        if len(tokens) >= 2:
            # find KINGSTON-like last token
            port_destination = tokens[-1]
            # loading could be last 2 or 3 tokens before destination
            port_loading = " ".join(tokens[-3:-1]) if len(tokens) >= 3 else tokens[0]
    fields["port_of_loading"] = make_field(True, port_loading, ev1 if port_loading else [], m1)
    fields["port_of_destination"] = make_field(True, port_destination, ev1 if port_destination else [], m1)

    gross_raw, ev, m = rx_first(text, r"peso\s+bruto\s*\(kg\)\s*[\r\n ]*([0-9\.,]+)")
    fields["gross_weight_kg"] = make_field(True, parse_number_mixed(gross_raw) if gross_raw else None, ev, m)

    net_raw, ev, m = rx_first(text, r"peso\s+neto\s*\(kg\)\s*[\r\n ]*([0-9\.,]+)")
    fields["net_weight_kg"] = make_field(True, parse_number_mixed(net_raw) if net_raw else None, ev, m)

    inc, ev, m = rx_first(text, r"\bincoterms\b.*?\b([A-Z]{3})\b", flags=re.IGNORECASE | re.DOTALL)
    fields["incoterm"] = make_field(True, inc, ev, m)

    curr, ev, m = line_after_label(text, r"^moneda\b")
    if not curr:
        curr, ev, m = rx_first(text, r"\bcurrency\b\s*[:\-]?\s*([A-Z]{3})\b")
    fields["currency"] = make_field(True, curr, ev, m)

    ncm, ev, m = rx_first(text, r"\bn\.c\.m\s*([0-9\.]+)")
    if not ncm:
        ncm, ev, m = rx_first(text, r"\bNCM\b\s*[:\-]?\s*([0-9\.]{6,})")
    fields["ncm"] = make_field(True, ncm, ev, m)

    cntr, ev, m = rx_first(text, r"\bCNTR\b\s*[\r\n ]*(\d+)\b")
    fields["container_count"] = make_field(True, int(cntr) if cntr else None, ev, m)

    # Exporter CNPJ
    cnpj_raw, ev, m = rx_first(text, r"\bC\.?N\.?P\.?J\.?\s*[:\-]?\s*([0-9\.\-\/]+)")
    fields["exporter_cnpj"] = make_field(True, parse_cnpj(cnpj_raw), ev, m)

    # Exporter name: heuristic - first long uppercase line (common in invoices)
    exporter, ev, m = rx_first(text, r"\n([A-Z0-9][A-Z0-9 &\.\-]{6,})\n", flags=re.MULTILINE)
    fields["exporter_name"] = make_field(True, exporter, ev, m)

    # Importer name: look for Consignee block
    importer, ev, m = inline_after_label(text, r"\bconsignee\b")
    if not importer:
        importer, ev, m = rx_first(text, r"\bConsignee\b\s*[:\-]?\s*([A-Z0-9 &\.\-]{3,})", flags=re.IGNORECASE)
    fields["importer_name"] = make_field(True, importer, ev, m)

    # Payment terms (not mandatory in your export list, but useful)
    pay, ev, m = rx_first(text, r"\bcobranza\b.*", flags=re.IGNORECASE)
    fields["payment_terms"] = make_field(False, pay, ev, m)

    return fields, warnings


def ex_packing_list(text: str) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    warnings: List[str] = []
    fields: Dict[str, Dict[str, Any]] = {}

    pk_no, ev, m = line_after_label(text, r"^packing\s*nr\.?$")
    if not pk_no:
        pk_no, ev, m = inline_after_label(text, r"packing\s*nr\.?")
    fields["packing_list_number"] = make_field(True, pk_no, ev, m)

    date, ev, m = rx_first(text, r"\b(\d{2}/\d{2}/\d{4})\b")
    fields["packing_date"] = make_field(True, date, ev, m)

    gross_raw, ev, m = rx_first(text, r"peso\s+bruto\s*\(kg\)\s*[\r\n ]*([0-9\.,]+)")
    fields["gross_weight_kg"] = make_field(True, parse_number_mixed(gross_raw) if gross_raw else None, ev, m)

    net_raw, ev, m = rx_first(text, r"peso\s+neto\s*\(kg\)\s*[\r\n ]*([0-9\.,]+)")
    fields["net_weight_kg"] = make_field(True, parse_number_mixed(net_raw) if net_raw else None, ev, m)

    ncm, ev, m = rx_first(text, r"\bn\.c\.m\s*([0-9\.]+)")
    fields["ncm"] = make_field(True, ncm, ev, m)

    inc, ev, m = rx_first(text, r"\bincoterms\b.*?\b([A-Z]{3})\b", flags=re.IGNORECASE | re.DOTALL)
    fields["incoterm"] = make_field(True, inc, ev, m)

    cntr, ev, m = rx_first(text, r"\bCNTR\b\s*[\r\n ]*(\d+)\b")
    fields["container_count"] = make_field(True, int(cntr) if cntr else None, ev, m)

    # Containers table lines (best-effort):
    containers: List[Dict[str, Any]] = []
    evs: List[str] = []
    for ln in text.splitlines():
        s = re.sub(r"\s{2,}", " ", ln.strip())
        # Example: TEMU1680211 M1024218 76,98
        m1 = re.match(r"^([A-Z]{4}\d{7})\s+([A-Z0-9]{6,})\s+([\d\.,]+)\b", s)
        if m1:
            containers.append({
                "container_number": m1.group(1),
                "seal": m1.group(2),
                "m2": parse_number_mixed(m1.group(3)),
                "raw_line": s
            })
            if len(evs) < 10:
                evs.append(s)

    fields["containers"] = make_field(True, containers if containers else None, evs, "line_parse")

    return fields, warnings


def parse_bl_container_lines(text: str) -> List[Dict[str, Any]]:
    """
    Parse BL draft container rows like:
      BMOU1157130 M1017120 2100,000 20 Dry 971 BOX, CARTON 26840,000 15,510
    """
    items: List[Dict[str, Any]] = []
    for ln in text.splitlines():
        s = re.sub(r"\s{2,}", " ", ln.strip())
        # container seal tara type packages ... gross measurement
        m = re.match(
            r"^([A-Z]{4}\d{7})\s+([A-Z0-9]+)\s+([\d\.,]+)\s+(\d+\s*Dry|\d+\s*HC|\d+\s*GP|\d+\s*RF|\d+\s*DV)\s+(\d+)\s+BOX.*?\s+([\d\.,]+)\s+([\d\.,]+)$",
            s,
            re.IGNORECASE
        )
        if m:
            items.append({
                "container_number": m.group(1),
                "seal": m.group(2),
                "tara_kg": parse_number_mixed(m.group(3)),
                "container_type": m.group(4),
                "packages": int(m.group(5)),
                "gross_weight_kg": parse_number_mixed(m.group(6)),
                "cbm_or_measurement": parse_number_mixed(m.group(7)),
                "raw_line": s
            })
    return items


def incoterm_freight_expectation(incoterm: str) -> Optional[str]:
    """
    Very simple heuristic (not a law):
    - C-terms (CFR/CIF/CPT/CIP) usually PREPAID
    - D-terms (DAP/DDP/DPU) usually PREPAID
    - E/F terms can be COLLECT (often) but can be prepaid too.
    """
    if not incoterm:
        return None
    inc = incoterm.upper().strip()
    if inc.startswith("C") or inc.startswith("D"):
        return "PREPAID"
    if inc in {"EXW", "FCA", "FOB", "FAS"}:
        return "COLLECT"
    return None


def ex_draft_bl(text: str) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    warnings: List[str] = []
    fields: Dict[str, Dict[str, Any]] = {}

    # Freight mode
    freight, ev, m = rx_first(text, r"FREIGHT\s+(PREPAID|COLLECT)", flags=re.IGNORECASE)
    freight_mode = freight.upper() if freight else None
    fields["freight_mode"] = make_field(True, freight_mode, ev, m)

    # Incoterm
    inc, ev2, m2 = rx_first(text, r"INCOTERM:\s*([A-Z]{3})", flags=re.IGNORECASE)
    fields["incoterm"] = make_field(True, inc, ev2, m2)

    # Compatibility warning (optional)
    if freight_mode and inc:
        expected = incoterm_freight_expectation(inc)
        if expected and expected != freight_mode:
            warnings.append(f"Possível inconsistência: incoterm {inc} normalmente sugere {expected}, mas BL está {freight_mode}.")

    # NCM / HS
    ncm, ev, m = rx_first(text, r"\bNCM(?:/NALADI)?[:\s]+([0-9\.]{6,})", flags=re.IGNORECASE)
    if not ncm:
        ncm, ev, m = rx_first(text, r"\bNCM:\s*(\d{8})\b", flags=re.IGNORECASE)
    fields["ncm"] = make_field(True, ncm, ev, m)

    # DU-E
    due, ev, m = rx_first(text, r"\bDUE:\s*([A-Z0-9\.\-\/]+)", flags=re.IGNORECASE)
    if due and due.strip() == ".":
        due = None
        ev = []
    fields["due"] = make_field(True, due, ev, m)

    # RUC
    ruc, ev, m = rx_first(text, r"\bRUC:\s*([A-Z0-9]+)", flags=re.IGNORECASE)
    fields["ruc"] = make_field(True, ruc, ev, m)

    # Booking (useful)
    booking, ev, m = rx_first(text, r"\b(SSZ\d{6,})\b")
    fields["booking_number"] = make_field(False, booking, ev, m)

    # Wooden packing
    wood, ev, m = rx_first(text, r"WOODEN\s+PACKAGE\s*:\s*([A-Z \/\-]+)", flags=re.IGNORECASE)
    fields["wooden_packing"] = make_field(True, wood, ev, m)

    # Containers list
    containers = parse_bl_container_lines(text)
    evc = [c["raw_line"] for c in containers[:10]] if containers else []
    fields["containers"] = make_field(True, containers if containers else None, evc, "line_parse")

    # Totals (cartons/packages and weights)
    cartons_raw, ev, m = rx_first(text, r"([\d\.,]+)\s+CARTONS", flags=re.IGNORECASE)
    cartons_val = None
    if cartons_raw:
        n = parse_number_mixed(cartons_raw)
        cartons_val = int(n) if n is not None else None
    fields["total_cartons"] = make_field(True, cartons_val, ev, m)

    net_raw, ev, m = rx_first(text, r"Net\s*Weight:\s*([\d\.,]+)\s*kg", flags=re.IGNORECASE)
    fields["net_weight_kg_total"] = make_field(True, parse_number_mixed(net_raw) if net_raw else None, ev, m)

    gross_raw, ev, m = rx_first(text, r"Gross\s*Weight:\s*([\d\.,]+)\s*kg", flags=re.IGNORECASE)
    fields["gross_weight_kg_total"] = make_field(True, parse_number_mixed(gross_raw) if gross_raw else None, ev, m)

    m3_raw, ev, m = rx_first(text, r"\b([\d\.,]+)\s*m³\b", flags=re.IGNORECASE)
    fields["cubic_meters_total"] = make_field(True, parse_number_mixed(m3_raw) if m3_raw else None, ev, m)

    # Exporter CNPJ / Exporter contact
    cnpj_raw, ev, m = rx_first(text, r"\bCNPJ:\s*([0-9\.\-\/]+)", flags=re.IGNORECASE)
    fields["exporter_cnpj"] = make_field(True, parse_cnpj(cnpj_raw), ev, m)

    # Basic "shipper" name heuristic
    shipper, ev, m = rx_first(text, r"\bShipper\b.*?\n([A-Z0-9 &\.\-]{4,})\n", flags=re.IGNORECASE | re.DOTALL)
    fields["exporter_name"] = make_field(True, shipper, ev, m)

    # Try phone/contact: extract any phone-like patterns from BL
    phones = parse_phone_candidates(text)
    fields["phones_found"] = make_field(False, phones if phones else None, phones[:8] if phones else [], "phone_heuristic")

    # Importer/Notify contacts (best-effort)
    importer, ev, m = rx_first(text, r"\bConsignee\b.*?\n([A-Z0-9 &\.\-]{4,})\n", flags=re.IGNORECASE | re.DOTALL)
    fields["importer_name"] = make_field(True, importer, ev, m)

    notify, ev, m = rx_first(text, r"\bNotify Party\b.*?\n([A-Z0-9 &\.\-]{4,})\n", flags=re.IGNORECASE | re.DOTALL)
    fields["notify_party_name"] = make_field(True, notify, ev, m)

    return fields, warnings


def ex_certificate_of_origin(text: str) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    warnings: List[str] = []
    fields: Dict[str, Dict[str, Any]] = {}

    inv, ev, m = rx_first(text, r"\b(I-\d{4}\/\d{2})\b")
    fields["invoice_number"] = make_field(True, inv, ev, m)

    date, ev, m = rx_first(text, r"\b(\d{2}/\d{2}/\d{4})\b")
    fields["certificate_date"] = make_field(True, date, ev, m)

    mode, ev, m = rx_first(text, r"\bBy Sea\b", flags=re.IGNORECASE)
    fields["transport_mode"] = make_field(True, "By Sea" if mode else None, ev, "regex")

    exporter, ev, m = rx_first(text, r"\bExporter\b.*?\n([A-Z0-9 &\.\-]{4,})\n", flags=re.IGNORECASE | re.DOTALL)
    fields["exporter_name"] = make_field(True, exporter, ev, m)

    importer, ev, m = rx_first(text, r"\bConsignee\b.*?\n([A-Z0-9 &\.\-]{4,})\n", flags=re.IGNORECASE | re.DOTALL)
    fields["importer_name"] = make_field(True, importer, ev, m)

    # KGS: may appear twice (net/gross). Pick min as net and max as gross.
    all_kgs, evs, mm = rx_findall(text, r"([\d\.,]+)\s*KGS", flags=re.IGNORECASE)
    nums = [parse_number_mixed(x) for x in all_kgs]
    nums = [x for x in nums if x is not None]
    if len(nums) >= 2:
        fields["net_weight_kg"] = make_field(True, min(nums), evs[:1], "regex_findall")
        fields["gross_weight_kg"] = make_field(True, max(nums), evs[:2], "regex_findall")
    else:
        fields["net_weight_kg"] = make_field(True, None, [], "regex_findall")
        fields["gross_weight_kg"] = make_field(True, None, [], "regex_findall")

    m2_raw, ev, m = rx_first(text, r"([\d\.,]+)\s*m²", flags=re.IGNORECASE)
    fields["total_m2"] = make_field(True, parse_number_mixed(m2_raw) if m2_raw else None, ev, m)

    return fields, warnings


def ex_container_data(text: str) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    warnings: List[str] = []
    fields: Dict[str, Dict[str, Any]] = {}

    inv, ev, m = rx_first(text, r"FATURA:\s*([A-Z0-9\-\/]+)", flags=re.IGNORECASE)
    fields["invoice_number"] = make_field(True, inv, ev, m)

    booking, ev, m = rx_first(text, r"BOOKING:\s*(SSZ\d+)", flags=re.IGNORECASE)
    fields["booking_number"] = make_field(True, booking, ev, m)

    # Container rows:
    # "1 TEMU1680211 M1024218 2100 30480"
    containers: List[Dict[str, Any]] = []
    evs: List[str] = []
    for ln in text.splitlines():
        s = re.sub(r"\s{2,}", " ", ln.strip())
        m1 = re.match(r"^\d+\s+([A-Z]{4}\d{7})\s+([A-Z0-9]{6,})\s+([\d\.,]+)\s+(\d+)\b.*$", s)
        if m1:
            containers.append({
                "container_number": m1.group(1),
                "seal": m1.group(2),
                "tara_kg": parse_number_mixed(m1.group(3)),
                "mgw": parse_number_mixed(m1.group(4)),
                "raw_line": s
            })
            if len(evs) < 12:
                evs.append(s)

    fields["containers"] = make_field(True, containers if containers else None, evs, "line_parse")

    return fields, warnings


def extract_by_kind(doc_kind: str, full_text: str) -> Tuple[Dict[str, Dict[str, Any]], List[str]]:
    if doc_kind == "commercial_invoice":
        return ex_commercial_invoice(full_text)
    if doc_kind == "packing_list":
        return ex_packing_list(full_text)
    if doc_kind == "draft_bl":
        return ex_draft_bl(full_text)
    if doc_kind == "certificate_of_origin":
        return ex_certificate_of_origin(full_text)
    if doc_kind == "container_data":
        return ex_container_data(full_text)
    return {}, []


# ---------------------------
# Output format
# ---------------------------

def build_output(stage01_filename: str, original_pdf: str, doc_kind: str,
                 fields: Dict[str, Dict[str, Any]], warnings: List[str]) -> dict:
    missing = [k for k, v in fields.items() if v.get("required") and not v.get("present")]
    return {
        "source": {
            "stage01_file": stage01_filename,
            "original_file": original_pdf,
            "doc_kind": doc_kind
        },
        "generated_at": now_iso(),
        "fields": fields,
        "missing_required_fields": missing,
        "warnings": warnings or []
    }


# ---------------------------
# Main
# ---------------------------

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="Pasta com *_extracted.json do Stage 01 (exportation)")
    ap.add_argument("--output", required=True, help="Pasta de saída do Stage 02 (fields) (exportation)")
    args = ap.parse_args()

    in_dir = Path(args.input)
    out_dir = Path(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)

    extracted_files = sorted(in_dir.glob("*_extracted.json"))
    if not extracted_files:
        raise SystemExit(f"Nenhum *_extracted.json encontrado em: {in_dir}")

    summary_items: List[dict] = []

    for p in extracted_files:
        stage01 = read_json(p)
        original_pdf = stage01.get("file") or p.name.replace("_extracted.json", ".pdf")

        full_text = join_pages(stage01)
        doc_kind = infer_doc_kind(original_pdf, full_text)

        fields, warns = extract_by_kind(doc_kind, full_text)

        out_obj = build_output(p.name, original_pdf, doc_kind, fields, warns)
        out_path = out_dir / p.name.replace("_extracted.json", "_fields.json")
        write_json(out_path, out_obj)

        summary_items.append({
            "file": original_pdf,
            "stage01": p.name,
            "doc_kind": doc_kind,
            "missing_required_fields": out_obj["missing_required_fields"],
            "warnings": out_obj["warnings"]
        })

    write_json(out_dir / "_stage02_summary.json", {
        "generated_at": now_iso(),
        "flow": "exportation",
        "items": summary_items
    })

    print("Concluído.")


if __name__ == "__main__":
    main()
